---
- name: Provision hopfencloud
  hosts: all
  vars:
    ansible_become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Install dependencies
      apt:
        update_cache: yes
        name:
          - nginx
          - htop
          - postgresql
          - gnupg2
          - libssl-dev
          # Required for ansible
          - acl
          - python3-psycopg2
    - name: Install key
      ansible.builtin.apt_key:
        state: present
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    - name: node repository
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_18.x bullseye main"
    - name: Install node
      ansible.builtin.apt:
        state: latest
        name: nodejs
    - name: Install yarn
      ansible.builtin.command:
        cmd: "npm install -g yarn"

    - name: Check for rustup
      ansible.builtin.stat:
        path: "/tmp/rustup.sh"
      register: rustup_file
    - name: Download rustup
      become_user: vagrant
      ansible.builtin.shell:
        cmd: "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh"
      when: not rustup_file.stat.exists
    - name: Execute installer
      become_user: vagrant
      ansible.builtin.shell:
        cmd: "sh /tmp/rustup.sh -y"
      when: not rustup_file.stat.exists
    - name: Install rorm-cli
      become_user: vagrant
      ansible.builtin.command:
        cmd: "/home/vagrant/.cargo/bin/cargo install rorm-cli"

    - name: Start postgres
      ansible.builtin.systemd:
        name: postgresql
        state: started
    - name: Create hopfencloud db user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
    - name: Create hopfencloud database
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        encoding: UTF-8
        owner: "{{ db_user }}"

    - name: Create hopfencloud group
      ansible.builtin.group:
        name: hopfencloud
    - name: Create hopfencloud user
      ansible.builtin.user:
        name: hopfencloud
        system: yes
        group: hopfencloud

    - name: Compile hopfencloud
      become_user: vagrant
      ansible.builtin.command:
        chdir: /vagrant
        cmd: "/home/vagrant/.cargo/bin/cargo build -r -p hopfencloud"
    - name: Copy to /usr/local/bin
      copy:
        remote_src: yes
        src: /vagrant/target/release/hopfencloud
        dest: /usr/local/bin/hopfencloud
        mode: 0755
        owner: root

    - name: Stop hopfencloud.service
      systemd:
        name: hopfencloud.service
        state: stopped
      ignore_errors: yes

    - name: Install systemd service
      copy:
        src: hopfencloud.service
        dest: /etc/systemd/system/hopfencloud.service
        owner: root
    - name: Restart hopfencloud
      systemd:
        enabled: yes
        name: hopfencloud.service
        state: restarted
    - name: Apply hopfencloud config.toml
      template:
        src: config.toml.jinja2
        dest: /etc/hopfencloud/config.toml
        owner: root
        group: hopfencloud
        mode: 0640

    - name: Install packages
      become_user: vagrant
      ansible.builtin.command:
        chdir: /vagrant/frontend
        cmd: "yarn install"
    - name: Build frontend
      become_user: vagrant
      ansible.builtin.command:
        chdir: /vagrant/frontend
        cmd: "yarn build"
    - name: Copy frontend to static dir
      ansible.builtin.copy:
        remote_src: yes
        src: /vagrant/frontend/build/
        dest: /var/www/hopfencloud

    - name: Apply nginx template
      template:
        src: hopfencloud.nginx.jinja2
        dest: /etc/nginx/sites-available/hopfencloud.conf
    - name: Link to enabled
      file:
        state: link
        owner: root
        group: root
        src: /etc/nginx/sites-available/hopfencloud.conf
        dest: /etc/nginx/sites-enabled/hopfencloud.conf
    - name: Reload nginx
      systemd:
        name: nginx
        state: reloaded

    - name: Restart hopfencloud
      systemd:
        name: hopfencloud.service
        state: restarted