version: "3.9"
services:
  hopfencloud:
    build: .
    depends_on:
      - database
    networks:
      - default
      - backend
    ports:
      - "8080:8080"

  database:
    image: "postgres:15"
    restart: always
    environment:
      POSTGRES_USER: "hopfencloud"
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - backend

networks:
  backend: