[Database]
# Must be one of [sqlite, mysql, postgresql]
# In case of sqlite only Driver and Name are required.
Driver = "sqlite"
# The name of the database or the path of the file in case of sqlite.
#
# sqlite specific:
#   You can specify either an absolute or relative path.
#   If a relative path is used, the file is created relative to
#   the WorkingDirectory setting from the service file.
Name = "hopfencloud.sqlite3"
# The following settings only apply if Driver is one of [mysql, postgresql]
Port = 3306
Host = "127.0.0.1"
User = "hopfencloud"
Password = ""

[Server]
# Path to the socket file used by hopfencli to send commands to the server.
# If using the provided service file, there should be no need to change this.
CLISockPath = "/run/hopfencloud/cli.sock"
ListenAddress = "127.0.0.1:8080"
# List of allowed host, port, protocol combination,
# the server can be accessed by.
#
# Note: If using port 80 or 443, the port can be omitted
AllowedHosts = [
    {Host = "127.0.0.1", Https = true}
]
# You can set this to true, if hopfencloud is deployed behin a reverse proxy
# and therefore has no TLS configured. You can still set your AllowedHosts
# to enforce the use of https:// and add the X-Forwarded-Proto header on
# your reverse proxy.
UseForwardedProtoHeader = false
# Limit of the maximum size of files that can be uploaded.
# Valid specifiers: K, M, G, T or P.
#
# Note:
#  Check the size of your tmp partition!
#  E.g.: MaxFileUpload is set to 2G, up to 10 simultaneous can be expected:
#  10 * 2G: Your tmp partition must hold at least 20G!
MaxFileUpload = "20M"

[Files]
# The path to the data directory
DataPath = "data/"
