[Server]
ListenAddress = "127.0.0.1"
ListenPort = 8080
# Generate this by executing hopfencloud gen-key
SecretKey = ""

[Database]
Driver = "Postgres"
Host = "127.0.0.1"
Port = 5432
Name = "hopfencloud"
User = "hopfencloud"
Password = "super-secure-password"

[Logging]
LogLevel = "info"
Path = "/var/log/hopfencloud/main.log"
RotationFileSize = "10 MB"
MaxRotationCount = 10

[[Logging.AdditionalFileLoggers]]
Name = "requests"
AddToMainLogger = true
Path = "/var/log/hopfencloud/requests.log"
RotationFileSize = "10 MB"
MaxRotationCount = 5
AlternativePattern = "{h([{d(%Y-%m-%d %H:%M:%S)} | {({l}):5.5}])} {m}{n}"
